name: quickshaw_app
description: QuickShaw ride-hailing demo app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  flutter_svg: ^2.0.10+1

  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis-latin-400-normal.ttf
          weight: 400
        - asset: assets/fonts/metropolis-latin-500-normal.ttf
          weight: 500
        - asset: assets/fonts/metropolis-latin-600-normal.ttf
          weight: 600
        - asset: assets/fonts/metropolis-latin-700-normal.ttf
          weight: 700
        - asset: assets/fonts/metropolis-latin-400-italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/metropolis-latin-500-italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/metropolis-latin-600-italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/metropolis-latin-700-italic.ttf
          weight: 700
          style: italic
